# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ImageDialogGUI.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(496, 300)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.AnimationData = QtWidgets.QGroupBox(Dialog)
        self.AnimationData.setObjectName("AnimationData")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.AnimationData)
        self.verticalLayout.setContentsMargins(-1, 0, -1, 9)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.AnimationData)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.Horizontal = QtWidgets.QSpinBox(self.AnimationData)
        self.Horizontal.setMinimum(0)
        self.Horizontal.setMaximum(999999999)
        self.Horizontal.setSingleStep(1)
        self.Horizontal.setObjectName("Horizontal")
        self.horizontalLayout_3.addWidget(self.Horizontal)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.DURL = QtWidgets.QRadioButton(self.AnimationData)
        self.DURL.setObjectName("DURL")
        self.gridLayout.addWidget(self.DURL, 1, 3, 1, 1)
        self.UDLR = QtWidgets.QRadioButton(self.AnimationData)
        self.UDLR.setChecked(False)
        self.UDLR.setObjectName("UDLR")
        self.gridLayout.addWidget(self.UDLR, 0, 2, 1, 1)
        self.LRUD = QtWidgets.QRadioButton(self.AnimationData)
        self.LRUD.setChecked(True)
        self.LRUD.setObjectName("LRUD")
        self.gridLayout.addWidget(self.LRUD, 0, 0, 1, 1)
        self.LRDU = QtWidgets.QRadioButton(self.AnimationData)
        self.LRDU.setObjectName("LRDU")
        self.gridLayout.addWidget(self.LRDU, 1, 0, 1, 1)
        self.RLDU = QtWidgets.QRadioButton(self.AnimationData)
        self.RLDU.setObjectName("RLDU")
        self.gridLayout.addWidget(self.RLDU, 1, 1, 1, 1)
        self.DULR = QtWidgets.QRadioButton(self.AnimationData)
        self.DULR.setObjectName("DULR")
        self.gridLayout.addWidget(self.DULR, 1, 2, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.AnimationData)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.Vertical = QtWidgets.QSpinBox(self.AnimationData)
        self.Vertical.setMinimum(0)
        self.Vertical.setMaximum(999999999)
        self.Vertical.setObjectName("Vertical")
        self.horizontalLayout_4.addWidget(self.Vertical)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 1, 1, 1)
        self.UDRL = QtWidgets.QRadioButton(self.AnimationData)
        self.UDRL.setObjectName("UDRL")
        self.gridLayout.addWidget(self.UDRL, 0, 3, 1, 1)
        self.RLUD = QtWidgets.QRadioButton(self.AnimationData)
        self.RLUD.setObjectName("RLUD")
        self.gridLayout.addWidget(self.RLUD, 0, 1, 1, 1)
        self.Custom = QtWidgets.QRadioButton(self.AnimationData)
        self.Custom.setObjectName("Custom")
        self.gridLayout.addWidget(self.Custom, 2, 3, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_4 = QtWidgets.QLabel(self.AnimationData)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_11.addWidget(self.label_4)
        self.FrameCount = QtWidgets.QSpinBox(self.AnimationData)
        self.FrameCount.setMinimum(0)
        self.FrameCount.setMaximum(999999999)
        self.FrameCount.setObjectName("FrameCount")
        self.horizontalLayout_11.addWidget(self.FrameCount)
        self.gridLayout.addLayout(self.horizontalLayout_11, 2, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.CSV = QtWidgets.QLineEdit(self.AnimationData)
        self.CSV.setObjectName("CSV")
        self.horizontalLayout_5.addWidget(self.CSV)
        self.Open = QtWidgets.QPushButton(self.AnimationData)
        self.Open.setObjectName("Open")
        self.horizontalLayout_5.addWidget(self.Open)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.addWidget(self.AnimationData)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.Path0 = QtWidgets.QLineEdit(Dialog)
        self.Path0.setObjectName("Path0")
        self.horizontalLayout.addWidget(self.Path0)
        self.Type0 = QtWidgets.QComboBox(Dialog)
        self.Type0.setObjectName("Type0")
        self.Type0.addItem("")
        self.Type0.addItem("")
        self.Type0.addItem("")
        self.Type0.addItem("")
        self.Type0.addItem("")
        self.horizontalLayout.addWidget(self.Type0)
        self.OpenFile0 = QtWidgets.QPushButton(Dialog)
        self.OpenFile0.setObjectName("OpenFile0")
        self.horizontalLayout.addWidget(self.OpenFile0)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.Path1 = QtWidgets.QLineEdit(Dialog)
        self.Path1.setObjectName("Path1")
        self.horizontalLayout_6.addWidget(self.Path1)
        self.Type1 = QtWidgets.QComboBox(Dialog)
        self.Type1.setObjectName("Type1")
        self.Type1.addItem("")
        self.Type1.addItem("")
        self.Type1.addItem("")
        self.Type1.addItem("")
        self.Type1.addItem("")
        self.horizontalLayout_6.addWidget(self.Type1)
        self.OpenFile1 = QtWidgets.QPushButton(Dialog)
        self.OpenFile1.setObjectName("OpenFile1")
        self.horizontalLayout_6.addWidget(self.OpenFile1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.Path2 = QtWidgets.QLineEdit(Dialog)
        self.Path2.setObjectName("Path2")
        self.horizontalLayout_7.addWidget(self.Path2)
        self.Type2 = QtWidgets.QComboBox(Dialog)
        self.Type2.setObjectName("Type2")
        self.Type2.addItem("")
        self.Type2.addItem("")
        self.Type2.addItem("")
        self.Type2.addItem("")
        self.Type2.addItem("")
        self.horizontalLayout_7.addWidget(self.Type2)
        self.OpenFile2 = QtWidgets.QPushButton(Dialog)
        self.OpenFile2.setObjectName("OpenFile2")
        self.horizontalLayout_7.addWidget(self.OpenFile2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.Path3 = QtWidgets.QLineEdit(Dialog)
        self.Path3.setObjectName("Path3")
        self.horizontalLayout_8.addWidget(self.Path3)
        self.Type3 = QtWidgets.QComboBox(Dialog)
        self.Type3.setObjectName("Type3")
        self.Type3.addItem("")
        self.Type3.addItem("")
        self.Type3.addItem("")
        self.Type3.addItem("")
        self.Type3.addItem("")
        self.horizontalLayout_8.addWidget(self.Type3)
        self.OpenFile3 = QtWidgets.QPushButton(Dialog)
        self.OpenFile3.setObjectName("OpenFile3")
        self.horizontalLayout_8.addWidget(self.OpenFile3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.Animated = QtWidgets.QCheckBox(Dialog)
        self.Animated.setObjectName("Animated")
        self.horizontalLayout_9.addWidget(self.Animated)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        self.Unkn3 = QtWidgets.QSpinBox(Dialog)
        self.Unkn3.setMinimum(-99999)
        self.Unkn3.setMaximum(99999)
        self.Unkn3.setSingleStep(4)
        self.Unkn3.setProperty("value", 4)
        self.Unkn3.setObjectName("Unkn3")
        self.horizontalLayout_9.addWidget(self.Unkn3)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_9)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.OK = QtWidgets.QPushButton(Dialog)
        self.OK.setObjectName("OK")
        self.horizontalLayout_2.addWidget(self.OK)
        self.Cancel = QtWidgets.QPushButton(Dialog)
        self.Cancel.setObjectName("Cancel")
        self.horizontalLayout_2.addWidget(self.Cancel)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.AnimationData.setTitle(_translate("Dialog", "Animated Load Order"))
        self.label_2.setText(_translate("Dialog", "Horizontal"))
        self.DURL.setText(_translate("Dialog", "DURL"))
        self.UDLR.setText(_translate("Dialog", "UDLR"))
        self.LRUD.setText(_translate("Dialog", "LRUD"))
        self.LRDU.setText(_translate("Dialog", "LRDU"))
        self.RLDU.setText(_translate("Dialog", "RLDU"))
        self.DULR.setText(_translate("Dialog", "DULR"))
        self.label_3.setText(_translate("Dialog", "Vertical"))
        self.UDRL.setText(_translate("Dialog", "UDRL"))
        self.RLUD.setText(_translate("Dialog", "RLUD"))
        self.Custom.setText(_translate("Dialog", "Custom"))
        self.label_4.setText(_translate("Dialog", "Frames"))
        self.Open.setText(_translate("Dialog", "Open CSV"))
        self.label.setText(_translate("Dialog", "Path:"))
        self.Type0.setItemText(0, _translate("Dialog", "Diffuse"))
        self.Type0.setItemText(1, _translate("Dialog", "Normal"))
        self.Type0.setItemText(2, _translate("Dialog", "RMT"))
        self.Type0.setItemText(3, _translate("Dialog", "Mask"))
        self.Type0.setItemText(4, _translate("Dialog", "Emissive"))
        self.OpenFile0.setText(_translate("Dialog", "..."))
        self.label_5.setText(_translate("Dialog", "Path:"))
        self.Type1.setItemText(0, _translate("Dialog", "Diffuse"))
        self.Type1.setItemText(1, _translate("Dialog", "Normal"))
        self.Type1.setItemText(2, _translate("Dialog", "RMT"))
        self.Type1.setItemText(3, _translate("Dialog", "Mask"))
        self.Type1.setItemText(4, _translate("Dialog", "Emissive"))
        self.OpenFile1.setText(_translate("Dialog", "..."))
        self.label_6.setText(_translate("Dialog", "Path:"))
        self.Type2.setItemText(0, _translate("Dialog", "Diffuse"))
        self.Type2.setItemText(1, _translate("Dialog", "Normal"))
        self.Type2.setItemText(2, _translate("Dialog", "RMT"))
        self.Type2.setItemText(3, _translate("Dialog", "Mask"))
        self.Type2.setItemText(4, _translate("Dialog", "Emissive"))
        self.OpenFile2.setText(_translate("Dialog", "..."))
        self.label_7.setText(_translate("Dialog", "Path:"))
        self.Type3.setItemText(0, _translate("Dialog", "Diffuse"))
        self.Type3.setItemText(1, _translate("Dialog", "Normal"))
        self.Type3.setItemText(2, _translate("Dialog", "RMT"))
        self.Type3.setItemText(3, _translate("Dialog", "Mask"))
        self.Type3.setItemText(4, _translate("Dialog", "Emissive"))
        self.OpenFile3.setText(_translate("Dialog", "..."))
        self.Animated.setText(_translate("Dialog", "Animated"))
        self.label_8.setText(_translate("Dialog", "Dynamic"))
        self.OK.setText(_translate("Dialog", "OK"))
        self.Cancel.setText(_translate("Dialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

